
import Airproject.dbConnection;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Gowshalini
 */
public class Cancel_Modify_Res extends javax.swing.JFrame {
  Connection con=null;
  PreparedStatement pst=null;
  ResultSet rs=null;
  static String rid;

    /**
     * Creates new form Cancel_Modify_Res
     */
    public Cancel_Modify_Res() {
        initComponents();
        dbConnection connect=new dbConnection();
        con=connect.ConnectDB();
        
        tableLoad();
      
        
    }
    
    public void tableLoad()
    {
        try{
              String q="select * from reservation where identity='1'";
              
            pst =con.prepareStatement(q);
            rs=pst.executeQuery(q);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtStartDate = new com.toedter.calendar.JDateChooser();
        txtEndDate = new com.toedter.calendar.JDateChooser();
        jCancel = new javax.swing.JButton();
        jmodify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserved Date", "Reservation ID", "Reserved", "Check In Date", "Check Outt Date", "Days", "Room No", "Price", "Special name", "AC/NON AC", "Reserved By ", "Break Fast", "Lunch", "Dinner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        label2.setText("Reservation Details");

        jLabel1.setText("Start Date");

        jLabel2.setText("End Date");

        jButton1.setText("View Reservation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtStartDate.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        txtStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStartDateKeyPressed(evt);
            }
        });

        txtEndDate.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        txtEndDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEndDateKeyPressed(evt);
            }
        });

        jCancel.setText("Cancel Reservation");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jmodify.setText("Modify Reservation");
        jmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 276, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(93, 93, 93)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1006, 1006, 1006))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(405, 405, 405))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(113, 113, 113)
                                .addComponent(jCancel)
                                .addGap(89, 89, 89)
                                .addComponent(jmodify)
                                .addContainerGap())))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCancel)
                                    .addComponent(jmodify))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
          
          Date startDate1=txtStartDate.getDate();
          Date endDate1=txtEndDate.getDate();
   
           String startDateString=startDate1.toString();
           String endDateString=endDate1.toString();
              
          
          
              
               try{
              //DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd "); 
                String formattedstartDate = df.format(startDate1); 
                String formattedEndDate = df.format(endDate1); 
               //Date startDate = df.parse(startDateString);
                 
               
        
            String q="select reservedDate,reservationId,reserved,checkindate,checkoutdate,days,roomNo,price,masterbedroom,ac,reservedBy,breakfast,lunch,dinner from reservation "
                    + "where    identity='1' and (reservedDate between '"+formattedstartDate+"' and '"+formattedEndDate+"' or reservedDate like '"+formattedEndDate+"%'    )";
            
            
           
            pst =con.prepareStatement(q);
            rs=pst.executeQuery(q);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           }
              
              
         catch(HeadlessException ex){
          JOptionPane.showMessageDialog(null,ex);
              }
      
      }
      catch(Exception ex)
      {
       JOptionPane.showMessageDialog(null,ex);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStartDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartDateKeyPressed
      
    }//GEN-LAST:event_txtStartDateKeyPressed

    private void txtEndDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndDateKeyPressed
     
    }//GEN-LAST:event_txtEndDateKeyPressed

    private void jmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyActionPerformed
 
      String reserved = null;
      String p="select reserved from reservation  where  reservationId='"+rid+"'";
          try{

          pst =con.prepareStatement(p);
          rs=pst.executeQuery(p);
          if(rs.next()){
                     reserved=rs.getString("reserved");
                        }
          
          if(reserved.equals("Reservation cancelled"))
              JOptionPane.showMessageDialog(null,"Can't modify cancelled Reservation");
          else if(reserved.equals("Stayed"))
               JOptionPane.showMessageDialog(null,"Can't modify Stayed Reservation");
          else{
            ModifyReservation hm=new ModifyReservation();
            hm.setVisible(true);
            this.dispose();
       
               }
          }
       
          catch(Exception ex)
          {
              JOptionPane.showMessageDialog(null,ex);
          }
        

    
    }//GEN-LAST:event_jmodifyActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int r=jTable1.getSelectedRow();
      
      rid=jTable1.getValueAt(r, 0).toString();
      Reservation re=new Reservation();
      re.setResId(jTable1.getValueAt(r, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
      
        try{
                  
       /* String t="select reservation from reservation where reservationId='"+rid+"' ";
        pst =con.prepareStatement(t);
        String res=pst.executeQuery();*/
        
        String q="update reservation set reserved ='Reservation cancelled' where reservationId='"+rid+"' ";
        pst =con.prepareStatement(q);
        pst.execute();
         tableLoad();
         
          JOptionPane.showMessageDialog(null,"Reservation cancelled successfully ", "Message",JOptionPane.INFORMATION_MESSAGE);
         
        String s="update room ro,reservation re set re.reserved ='Reservation cancelled',ro.reserved ='Reservation cancelled' where re.reservationId='"+rid+"' and re.roomNo=ro.roomNo ";
        pst =con.prepareStatement(s);
        pst.execute();
          
        }
        catch(Exception ex )
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel_Modify_Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel_Modify_Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel_Modify_Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel_Modify_Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_Modify_Res().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jmodify;
    private java.awt.Label label2;
    private com.toedter.calendar.JDateChooser txtEndDate;
    private com.toedter.calendar.JDateChooser txtStartDate;
    // End of variables declaration//GEN-END:variables
}
